Html forms (Noah Khayat)
NaeemK1188/c1224-code-solutions pull request #24
Opened 2024-12-18 08:45 UTC by NaeemK1188

![Screenshot (52)](https://github.com/user-attachments/assets/3d881b71-28e6-4836-aa57-ec1fb34acfe4)

2024-12-18 17:35 UTC, shawnkost requested changes
Misisng some `for` & `id` attributes to connect your `label`s and `input`s

2024-12-18 17:35 UTC, shawnkost commented on html-forms/index.html
> +      <label>Email</label>
The label needs a `for` that matches the `id` of the `input` you want to associate it with

2024-12-18 17:35 UTC, shawnkost commented on html-forms/index.html
> +      <label>Why is Coding Cool?</label>
The label needs a `for` that matches the `id` of the `input` you want to associate it with

2024-12-18 17:35 UTC, shawnkost commented on html-forms/index.html
> +      <label>Comments</label>
The label needs a `for` that matches the `id` of the `input` you want to associate it with

2024-12-18 20:19 UTC, NaeemK1188 commented
adding form and id attributes to the missing parts

2024-12-19 16:57 UTC, shawnkost approved these changes
👍🏻

2024-12-19 17:35 UTC, merged